#!/usr/bin/env bash
# Regenerate the Homebrew formula for a published release tag.
#
# The `release` workflow attaches a `*.tar.gz.sha256` sidecar for each target to
# the GitHub Release. This reads those, so the formula's checksums always match
# the exact published artifacts (no manual sha copying).
#
# Usage:
#   scripts/update-formula.sh v0.1.0 > ../homebrew-tap/Formula/promtect.rb
#   (then commit + push the tap repo)
set -euo pipefail

tag="${1:?usage: update-formula.sh vX.Y.Z}"
ver="${tag#v}"
repo="${PROMTECT_REPO:-Amitk3293/promtect}"
base="https://github.com/${repo}/releases/download/${tag}"

# Pull the sha256 from a verified local candidate when PROMTECT_ASSET_DIR is
# set; otherwise read the already-published sidecar from GitHub. Release CI uses
# the local path so formula generation cannot publish or depend on a partial
# release.
sha() {
  sidecar="promtect-${tag}-$1.tar.gz.sha256"
  if [ -n "${PROMTECT_ASSET_DIR:-}" ]; then
    [ -f "${PROMTECT_ASSET_DIR}/${sidecar}" ] \
      || { echo "missing ${sidecar}" >&2; exit 1; }
    awk -v archive="${sidecar%.sha256}" \
      'length($1) == 64 && $1 !~ /[^0-9a-f]/ && $2 == archive && NF == 2 { print $1; found = 1 } END { exit !found }' \
      "${PROMTECT_ASSET_DIR}/${sidecar}"
  else
    gh release download "$tag" -R "$repo" -p "$sidecar" -O - \
      | awk -v archive="${sidecar%.sha256}" \
          'length($1) == 64 && $1 !~ /[^0-9a-f]/ && $2 == archive && NF == 2 { print $1; found = 1 } END { exit !found }'
  fi
}

arm_mac="$(sha aarch64-apple-darwin)"
x86_mac="$(sha x86_64-apple-darwin)"
arm_lin="$(sha aarch64-unknown-linux-gnu)"
x86_lin="$(sha x86_64-unknown-linux-gnu)"

cat <<RB
# Generated by scripts/update-formula.sh for ${tag} — do not hand-edit checksums.
class Promtect < Formula
  desc "Mask secrets out of AI coding tool requests before they reach the model"
  homepage "https://promtect.org"
  version "${ver}"
  license :cannot_represent

  on_macos do
    on_arm do
      url "${base}/promtect-${tag}-aarch64-apple-darwin.tar.gz"
      sha256 "${arm_mac}"
    end
    on_intel do
      url "${base}/promtect-${tag}-x86_64-apple-darwin.tar.gz"
      sha256 "${x86_mac}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/promtect-${tag}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${arm_lin}"
    end
    on_intel do
      url "${base}/promtect-${tag}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${x86_lin}"
    end
  end

  def install
    bin.install "promtect"
  end

  test do
    assert_match "PASS", shell_output("#{bin}/promtect selftest")
  end
end
RB
